apiVersion: v1
kind: Template
metadata:
  name: core-ui-components
  annotations:
    iconClass: icon-js
    tags: storybook, nodejs, nx
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/display-name: "Core UI Components Stack"
    description: Build DIO core-  ui-components stacks
message: "The following service(s) have been created in your project: ${NAME}.\n\nMore message text here"
parameters:
  - name: NAME
    displayName: "Name"
    description: "The name assigned to all of the frontend objects defined in this template."
    required: true
    value: "core-ui-components"
  - name: NAMESPACE
    displayName: "Namespace"
    description: "The OpenShift Namespace where the ImageStream resides."
    required: true
    value: "openshift"
  - name: MEMORY_LIMIT
    displayName: "Memory Limit"
    description: "Maximum amount of memory the container can use."
    required: true
    value: "512Mi"
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    value: "git@gitlab.gov.ab.ca:dio/core/ui-components.git"
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: The branch name for the application
    displayName: Source Branch
    value: master
    required: true
  - name: SOURCE_REPOSITORY_DIR
    description: The location within the source repo of the application
    displayName: Source Directory
    value: .
    required: true
  - name: OUTPUT_DIR
    description: The location of the compiled static files from your web apps builder
    displayName: Output Directory
    value: build
    required: false
  - name: YARN_ENABLED
    description: A flag to enable the use of the Yarn package manager
    displayName: Yarn Enabled
    value: "true"
    required: false
  - name: GITLAB_WEBHOOK_SECRET
    description: A secret string used to configure the GitLab webhook.
    displayName: GitLab Webhook Secret
    required: true
    from: '[a-zA-Z0-9]{40}'
    generate: expression
  - name: UUID
    description: Fixed UUID used to distinguish the app with same app labels
    required: true
    value: c4ab458b-bffa-4607-bcb2-2f3dc4a16624
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: '${NAME}-${SOURCE_REPOSITORY_REF}'
      labels:
        app: '${NAME}-${SOURCE_REPOSITORY_REF}'
        appWithUUID: '${NAME}-${SOURCE_REPOSITORY_REF}-${UUID}'
    spec: {}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: '${NAME}-${SOURCE_REPOSITORY_REF}-fetch'
      labels:
        app: '${NAME}-${SOURCE_REPOSITORY_REF}'
        appWithUUID: '${NAME}-${SOURCE_REPOSITORY_REF}-${UUID}'
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}-${SOURCE_REPOSITORY_REF}:latest'
      postCommit: {}
      resources: {}
      source:
        git:
          uri: '${SOURCE_REPOSITORY_URL}'
          ref: '${SOURCE_REPOSITORY_REF}'
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          env:
            - name: OUTPUT_DIR
              value: ${OUTPUT_DIR}
            - name: YARN_ENABLED
              value: ${YARN_ENABLED}
          from:
            kind: DockerImage
            name: 'nodeshift/ubi8-s2i-web-app:10.x'
      triggers:
        - gitlab:
            secret: '${GITLAB_WEBHOOK_SECRET}'
          type: GitLab
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
    status:
      lastVersion: 0
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: '${NAME}-${SOURCE_REPOSITORY_REF}-fetch'
      labels:
        app: '${NAME}-${SOURCE_REPOSITORY_REF}'
        appWithUUID: '${NAME}-${SOURCE_REPOSITORY_REF}-${UUID}'
    spec:
      template:
        spec:
          containers:
            - image: ${NAME}-${SOURCE_REPOSITORY_REF}:latest'
              name: '${NAME}-${SOURCE_REPOSITORY_REF}'
              securityContext:
                privileged: false
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              resources:
                limits:
                  memory: ${MEMORY_LIMIT}
        metadata:
          labels:
            app: '${NAME}-${SOURCE_REPOSITORY_REF}'
      replicas: 1
      selector:
        app: '${NAME}-${SOURCE_REPOSITORY_REF}'
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - '${NAME}-${SOURCE_REPOSITORY_REF}'
            from:
              kind: ImageStreamTag
              name: '${NAME}-${SOURCE_REPOSITORY_REF}:latest'
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: '${NAME}-${SOURCE_REPOSITORY_REF}'
      name: '${NAME}-${SOURCE_REPOSITORY_REF}'
    spec:
      ports:
        - name: http
          port: 8080
      selector:
        app: '${NAME}-${SOURCE_REPOSITORY_REF}'
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: '${NAME}-${SOURCE_REPOSITORY_REF}'
        appWithUUID: '${NAME}-${SOURCE_REPOSITORY_REF}-${UUID}'
      name: '${NAME}-${SOURCE_REPOSITORY_REF}'
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: '${NAME}-${SOURCE_REPOSITORY_REF}'