name: Pull Request Check

on:
  pull_request:
    branches:
      - main
      - beta

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm ci
      # Run with the target branch as the base.
      - name: Lint
        run: npm run affected:lint -- --base=origin/${{ github.base_ref }}
      - name: Test
        run: npm run affected:test -- --base=origin/${{ github.base_ref }}
      - name: Build
        run: npm run affected:build -- --base=origin/${{ github.base_ref }}
